services:
  database:
    image: database:1.0.0
    container_name: postgres-c-mw
    env_file:
      - .env
    user: postgres
    environment:
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DATABASE}
    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
      - 6779:${POSTGRES_PORT}
    volumes:
      - database-v-mw:/var/lib/postgresql/data
    command: "-p 6779"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -p 6779 -U postgres -d my_db"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 0s

volumes:
  database-v-mw:
    name: "database-v-mw"